export const RIDE_TABLE_COLUMNS = [
   'FROM',
   'TO',
   'DATE AND TIME',
   'NO.OF PEOPLE',
   'LAGUAGE QUANTITY',
   'ACCEPTED PERSON DETAILS'
]

export const ASSET_TABLE_COLUMNS = [
   'FROM',
   'TO',
   'DATE AND TIME',
   'ASSET QUANTITY',
   'ASSET TYPE',
   'ASSET SENSITIVITY',
   'WHOM TO DELIVER',
   'ACCEPTED PERSON DETAILS'
]
